# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20170609_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
    ]
