# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20170609_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
