# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20170609_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='amount_currency',
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
